### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by ghb162** [UsernameFull/majsoul_mod#3]
这两天游戏更新了，添加了单独的角色音量设置，
使用mod后角色音量设置不生效，角色说话超大声的

**Comment by UsernameFull** [comment]
已更新，应该没问题了

**Comment by ghb162** [comment]
> 已更新，应该没问题了



> 已更新，应该没问题了

**Comment by ghb162** [comment]
> 已更新，应该没问题了

 感谢！！

**Comment by ghb162** [comment]
> 已更新，应该没问题了
报菜名还是很大声。。

**Comment by UsernameFull** [comment]
在友人房试了一下，报菜名音量应该正常了

**Comment by ghb162** [comment]
> 在友人房试了一下，报菜名音量应该正常了

辛苦了
