### ISSUE TITLE
今天维护后进主界面卡死

### ISSUE THREAD

**Issue by AlleriaWindy** [UsernameFull/majsoul_mod#5]
Console信息：
```
code.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
    at t._nextchar (code.js:1)
    at t.<anonymous> (code.js:1)
    at t.e.run (code.js:1)
    at t.n._update (code.js:1)
    at e.o.render (code.js:1)
    at e.o._loop (code.js:1)
    at a (code.js:1)
```

![image](https://user-images.githubusercontent.com/19866685/56721250-1570e480-6777-11e9-874b-33d3cf0fc05e.png)
大概在这行出错。我用的是油猴+脚本，关闭插件后正常。有劳大佬看下。顺便问下如何调试这种压缩到一行的js代码？我打了断点直接卡死了。。。

**Comment by mkktheone** [comment]
看8懂，等好心人解决

**Comment by UsernameFull** [comment]
> Console信息：
> 
> ```
> code.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
>     at t._nextchar (code.js:1)
>     at t.<anonymous> (code.js:1)
>     at t.e.run (code.js:1)
>     at t.n._update (code.js:1)
>     at e.o.render (code.js:1)
>     at e.o._loop (code.js:1)
>     at a (code.js:1)
> ```
> ![image](https://user-images.githubusercontent.com/19866685/56721250-1570e480-6777-11e9-874b-33d3cf0fc05e.png)
> 大概在这行出错。我用的是油猴+脚本，关闭插件后正常。有劳大佬看下。顺便问下如何调试这种压缩到一行的js代码？我打了断点直接卡死了。。。

本来已经更好了，一觉醒来又更新了。。。可能要晚点才能更好了
如果打断点调试卡死，请砸掉电脑并换外星人（滑稽

**Comment by mrd-mrd** [comment]
用雀魂plus也卡死

**Comment by UsernameFull** [comment]
刚完成更新，试试

**Comment by mrd-mrd** [comment]
> 刚完成更新，试试

好了，没卡死了，谢谢大佬

**Comment by mrd-mrd** [comment]
> 刚完成更新，试试

有bug,换角色的话我出的牌会在别家显示，多出几次牌就会让刷新重启游戏，

**Comment by mrd-mrd** [comment]
只能用默认的八木唯

**Comment by AlleriaWindy** [comment]
我回家试了下，无论用谁，都会看着自己手牌别家出牌，如图：
![image](https://user-images.githubusercontent.com/19866685/56848567-3e32de80-691d-11e9-95cc-6afde7abd7cf.png)

**Comment by UsernameFull** [comment]
> 我回家试了下，无论用谁，都会看着自己手牌别家出牌，如图：
> ![image](https://user-images.githubusercontent.com/19866685/56848631-dfba3000-691d-11e9-9cf4-e63df77ae679.png)
> 我想是不是友人房玩家顺序会在加载时打乱？我以前尝试修改大佬的代码让友人房电脑随机角色，但是顺序上一直不符合我的预期，不过既然是随机我也没有在意，会不会是这个原因？

这里的确有问题，我测试的时候没仔细，正在改

**Comment by UsernameFull** [comment]
应该改好了，但角色切换界面还有个小bug，不影响使用，明天再弄

**Comment by AlleriaWindy** [comment]
大佬辛苦了~
