### ISSUE TITLE
在启动时/加载牌谱时卡死

### ISSUE THREAD

**Issue by xiaoas** [UsernameFull/majsoul_mod#7]
![加载时卡死](https://user-images.githubusercontent.com/14904657/58333557-445ea100-7e70-11e9-9579-7e14717703d0.png)
加载到98%时卡死 有时候有 有时无
![加载牌谱](https://user-images.githubusercontent.com/14904657/58333642-6fe18b80-7e70-11e9-9ca2-9a1d3a146bf3.png)
加载牌谱会卡死是这次更新新引入的bug

**Comment by UsernameFull** [comment]
这俩天要考试，之后再更
