### ISSUE TITLE
还是可能会报错QAQ

### ISSUE THREAD

**Issue by xiaoas** [UsernameFull/majsoul_mod#8]
![image](https://user-images.githubusercontent.com/14904657/59076428-8d9b0000-8908-11e9-9f38-6c16ba38986f.png)
雀魂Plus v1.12.0-beta.4

**Comment by xiaoas** [comment]
另外能不能在配置文件中加入不用装饰的功能QAQ

**Comment by UsernameFull** [comment]
请问是在进行什么操作时报的错

**Comment by xiaoas** [comment]
就是初始加载啊。。。加载到98% 或者更少就卡住了
